# 配置文件

DAILY_TIME: "6:00" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2019-08-31" # 纪念日
CITY: "郑州"

BIRTHDAY:
  - "05-01"

APP_ID: "wxae7ba34e6556259e"
APP_SECRET: "590fb4cfa3188b622ab33fda5e115e22"

USER_ID: 
  - "ovIAy5_NqnO9-avGQ_mekgcXziOc"
 # - "USER ID 2" # 你可以通过配置多个USER_ID来设置多个接受者，如果接受者只有一人删除本行即可
TEMPLATE_ID: "DrfkCv17CvfxHMriF8-R6ADVRUZmBF0njK-vqcc854Y"
